version: "3"
# https://www.elastic.co/guide/en/kibana/5.6/install.html
# https://github.com/medcl/elasticsearch-analysis-ik
# https://github.com/medcl/elasticsearch-analysis-pinyin
# https://github.com/ElasticHQ/elasticsearch-HQ
# https://docs.search-guard.com/latest/search-guard-versions
# https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html
# https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html
# https://github.com/lmenezes/cerebro
services:
  kibana:
    container_name: kibana
    image: kibana:5.6
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticsearch-kibana

  elasticsearch:
    container_name: elasticsearch
    image: zhiqiangwang/elasticsearch:5.6
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elasticsearch-kibana

networks:
  elasticsearch-kibana:
    driver: bridge
